/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_pangb_jnitestproject_NdkJniUtils */

#ifndef _Included_com_example_pangb_jnitestproject_NdkJniUtils
#define _Included_com_example_pangb_jnitestproject_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_pangb_jnitestproject_NdkJniUtils
 * Method:    generateKey
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_pangb_jnitestproject_NdkJniUtils_generateKey
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
